import { Product } from './types';

export const HERO_SLIDES: Product[] = [
  {
    id: 'hero-1',
    name: 'Nike Air Max 6 Rings',
    category: "Men's Shoe",
    price: 190,
    image: '/yellow.png',
    themeColor: '#fdbd1a', // Yellow
    description: 'The Nike 6 Rings Men\'s Shoe celebrates a legendary career with classic design lines and detailing for streamlined hoops style.',
  },
  {
    id: 'hero-2',
    name: 'Nike Air Max 720 Neo',
    category: "Running Shoe",
    price: 210,
    image: '/red.png',
    themeColor: '#e11d48', // Red
    description: 'The Air Max 720 features the tallest Air unit yet, offering more air underfoot for unimaginable all-day comfort.',
  },
  {
    id: 'hero-3',
    name: 'Nike Zoom Fly Black',
    category: "Racing Shoe",
    price: 180,
    image: '/black.png',
    themeColor: '#1a1a1a', // Black
    description: 'Fast enough for race day, durable enough for your daily routine. The Zoom Fly is built for speed and endurance.',
  }
];

export const TOP_PICKS: Product[] = [
  // ROW 1
  {
    id: '1',
    name: 'Nike Kyrie 5 x Friends',
    category: "Men's Shoe",
    price: 154.95,
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?q=80&w=800&auto=format&fit=crop',
    colors: 1,
    description: 'A special collaboration featuring the iconic 90s show colors on the responsive Kyrie 5 platform.',
  },
  {
    id: '2',
    name: 'Nike Air Max 720',
    category: "Men's Shoe",
    price: 154.95,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop',
    colors: 3,
    description: 'Experience pure cushioning with the largest Air unit to date, designed specifically for lifestyle comfort.',
  },
  {
    id: '3',
    name: 'Nike Zoom Pegasus 35',
    category: "Running Shoe",
    price: 159.95,
    image: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?q=80&w=800&auto=format&fit=crop',
    colors: 1,
    description: 'The versatile runner returns with a faster feel and a premium Flymesh upper.',
  },
  // ROW 2
  {
    id: '4',
    name: 'Nike React Infinity Run',
    category: "Men's Shoe",
    price: 145,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=800&auto=format&fit=crop',
    colors: 4,
    description: 'Designed to help reduce injury and keep you on the run. More foam and improved upper details.',
  },
  {
    id: '5',
    name: 'Nike Air VaporMax Plus',
    category: "Lifestyle",
    price: 210,
    image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=800&auto=format&fit=crop',
    colors: 2,
    description: 'Classic 1998 design meets modern VaporMax Air technology for a gravity-defying feel.',
  },
  {
    id: '6',
    name: 'Nike Blazer Mid 77',
    category: "Vintage Shoe",
    price: 100,
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=800&auto=format&fit=crop',
    colors: 5,
    description: 'Timeless style meets modern construction in this court classic from the 70s.',
  },
  // ROW 3
  {
    id: '7',
    name: 'Nike Dunk Low Retro',
    category: "Lifestyle",
    price: 110,
    image: 'https://images.unsplash.com/photo-1628253747716-0c4f5c90fdda?q=80&w=800&auto=format&fit=crop',
    colors: 3,
    description: 'The basketball icon of the 80s returns with classic materials and heritage hoops flair.',
  },
  {
    id: '8',
    name: 'Nike Air Force 1 07',
    category: "Men's Shoe",
    price: 110,
    image: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?q=80&w=800&auto=format&fit=crop',
    colors: 2,
    description: 'The radiance lives on in the Nike Air Force 1 07, the b-ball OG that puts a fresh spin on what you know best.',
  },
  {
    id: '9',
    name: 'Nike Metcon 8',
    category: "Training Shoe",
    price: 130,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop',
    colors: 4,
    description: 'Lighter and more breathable than previous editions, the Metcon 8 is the gold standard for your workouts.',
  },
  {
    id: '10',
    name: 'Nike Waffle One',
    category: "Mens Shoe",
    price: 115,
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?q=80&w=800&auto=format&fit=crop',
    colors: 6,
    description: 'Bringing a new look to the Waffle sneaker family, it balances everything you love about heritage running.',
  },
  {
    id: '11',
    name: 'Nike Air Huarache',
    category: "Mens Shoe",
    price: 125,
    image: 'https://images.unsplash.com/photo-1543508282-6319a3e2621f?q=80&w=800&auto=format&fit=crop',
    colors: 2,
    description: 'Built to fit your foot and designed for comfort, it features soft leather accents and super-breathable fabric.',
  },
  {
    id: '12',
    name: 'Nike Pegasus Turbo Next Nature',
    category: "Running Shoe",
    price: 150,
    image: 'https://images.unsplash.com/photo-1582588673323-28956488d011?q=80&w=800&auto=format&fit=crop',
    colors: 3,
    description: 'Let this respected stallion help you log the hard miles. Complete with a lighter, responsive, repurposed foam.',
  },
  {
    id: '13',
    name: 'Nike Air Max Pre-Day',
    category: "Mens Shoe",
    price: 135,
    image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=800&auto=format&fit=crop',
    colors: 4,
    description: 'Taking the classic look of heritage Nike running into a new realm, the Air Max Pre-Day brings a fast-paced look.',
  },
  {
    id: '14',
    name: 'Nike Air Max Dawn',
    category: "Mens Shoe",
    price: 115,
    image: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?q=80&w=800&auto=format&fit=crop',
    colors: 2,
    description: 'Rooted in track DNA, the Air Max Dawn is made from at least 20% recycled material by weight.',
  },
  {
    id: '15',
    name: 'Nike SB Dunk Low',
    category: "Skate Shoe",
    price: 115,
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=800&auto=format&fit=crop',
    colors: 1,
    description: 'The legendary Dunk Low returns in premium materials and classic color-blocking.',
  },
];

export const ALL_PRODUCTS: Product[] = [
  ...TOP_PICKS,
  {
    id: '101',
    name: 'Nike Jordan 11 Retro',
    category: 'Lifestyle',
    price: 250,
    image: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=800&auto=format&fit=crop',
    isNew: true,
    colors: 1,
    description: 'Celebrate the history of flight with one of the most beloved Air Jordan silhouettes of all time.',
    sizes: ['7', '8', '9', '10', '11', '12'],
    features: ['Patent leather upper', 'Carbon fiber shank', 'Full-length composite plate'],
  },
  {
    id: '102',
    name: 'Nike Jordan 6 Rings',
    category: 'Basketball',
    price: 190,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop',
    colors: 3,
    description: 'The Jordan 6 Rings incorporates key features from each shoe worn during MJ\'s championship series.',
    sizes: ['7', '8', '9', '10', '11', '12'],
    features: ['Zoom Air units', 'Phylon midsole', 'Genuine leather upper'],
  },
];
