import { Product } from './types';

// ==================== HERO SLIDES ====================
export const HERO_SLIDES: Product[] = [
  {
    id: 'hero-1',
    name: 'Nike Air Max 6 Rings',
    category: "Men's Shoe",
    price: 190,
    image: '/yellow.png',
    themeColor: '#fdbd1a',
    description: 'The Nike 6 Rings Men\'s Shoe celebrates a legendary career with classic design lines and detailing for streamlined hoops style.',
  },
  {
    id: 'hero-2',
    name: 'Nike Air Max 720 Neo',
    category: "Running Shoe",
    price: 210,
    image: '/red.png',
    themeColor: '#e11d48',
    description: 'The Air Max 720 features the tallest Air unit yet, offering more air underfoot for unimaginable all-day comfort.',
  },
  {
    id: 'hero-3',
    name: 'Nike Zoom Fly Black',
    category: "Racing Shoe",
    price: 180,
    image: '/black.png',
    themeColor: '#1a1a1a',
    description: 'Fast enough for race day, durable enough for your daily routine. The Zoom Fly is built for speed and endurance.',
  }
];

// ==================== MEN'S PRODUCTS ====================
export const MEN_PRODUCTS: Product[] = [
  {
    id: 'men-1',
    name: 'Nike Shox TL',
    category: "Men's Shoe",
    price: 210,
    image: '/shoe1.jpeg',
    colors: 2,
    description: 'The iconic Nike Shox TL returns with responsive cushioning columns and futuristic streetwear styling.',
  },
  {
    id: 'men-2',
    name: 'Nike Dunk Low Chicago',
    category: "Lifestyle",
    price: 130,
    image: '/shoe2.jpeg',
    colors: 3,
    description: 'A timeless Dunk Low inspired by the legendary Chicago colorway with bold varsity red overlays.',
  },
  {
    id: 'men-3',
    name: 'Nike Dunk Low Spartan Green',
    category: "Lifestyle",
    price: 125,
    image: '/shoe3.jpeg',
    colors: 2,
    description: 'Classic college-inspired green and white blocking brings vintage basketball energy to the streets.',
  },
  {
    id: 'men-4',
    name: 'Air Jordan 1 High Chicago',
    category: "Basketball Shoe",
    price: 185,
    image: '/shoe4.jpeg',
    colors: 1,
    description: 'One of the most legendary sneakers ever made, featuring the unmistakable Chicago Bulls color scheme.',
  },
  {
    id: 'men-5',
    name: 'Nike SB Dunk Low Grey Gum',
    category: "Skate Shoe",
    price: 120,
    image: '/shoe5.jpeg',
    colors: 2,
    description: 'Minimal grey suede upper paired with gum soles for a clean everyday skate aesthetic.',
  },
  {
    id: 'men-6',
    name: 'Levi’s x Nike Dunk Low',
    category: "Collaboration",
    price: 175,
    image: '/shoe6.jpeg',
    colors: 2,
    description: 'Premium denim textures and classic Dunk design combine in this standout collaboration pair.',
  },
  {
    id: 'men-7',
    name: 'Nike Air Force 1 Low',
    category: "Lifestyle",
    price: 110,
    image: '/shoe7.jpeg',
    colors: 3,
    description: 'The timeless Air Force 1 silhouette with clean leather construction and everyday versatility.',
  },
  {
    id: 'men-8',
    name: 'Nike Dunk Low Mocha',
    category: "Lifestyle",
    price: 135,
    image: '/shoe8.jpeg',
    colors: 2,
    description: 'Earth-tone mocha overlays meet smooth leather details in this modern Dunk Low colorway.',
  },
  {
    id: 'men-9',
    name: 'Nike Dunk Low Georgetown',
    category: "Lifestyle",
    price: 130,
    image: '/shoe9.jpeg',
    colors: 2,
    description: 'Inspired by Georgetown University colors with smooth navy overlays and heritage basketball vibes.',
  },
  {
    id: 'men-10',
    name: 'Nike Air Force 1 Triple White',
    category: "Men's Shoe",
    price: 115,
    image: '/shoe10.jpeg',
    colors: 1,
    description: 'The all-white AF1 remains one of the cleanest and most iconic sneakers in footwear history.',
  },
  {
    id: 'men-11',
    name: 'Travis Scott x Nike Dunk Low',
    category: "Collaboration",
    price: 260,
    image: '/shoe11.jpeg',
    colors: 4,
    description: 'Wild textures, plaid overlays, and rope laces define this iconic Travis Scott Dunk collaboration.',
  },
  {
    id: 'men-12',
    name: 'Nike Dunk Low Vintage Green',
    category: "Lifestyle",
    price: 125,
    image: '/shoe12.jpeg',
    colors: 2,
    description: 'Vintage-inspired green overlays paired with a retro sail midsole for a timeless aesthetic.',
  },
  {
    id: 'men-13',
    name: 'Nike Dunk Low What The',
    category: "Lifestyle",
    price: 170,
    image: '/shoe13.jpeg',
    colors: 6,
    description: 'A colorful mashup of multiple Dunk inspirations fused into one bold sneaker statement.',
  },
  {
    id: 'men-14',
    name: 'Nike Dunk Low Black Orange',
    category: "Lifestyle",
    price: 120,
    image: '/shoe14.jpeg',
    colors: 2,
    description: 'Sharp black and orange contrasts deliver a bold streetwear-ready Dunk Low design.',
  },
  {
    id: 'men-15',
    name: 'Nike Dunk Low Syracuse Inspired',
    category: "Lifestyle",
    price: 128,
    image: '/shoe15.jpeg',
    colors: 2,
    description: 'Bright orange overlays inspired by the famous Syracuse Dunk color palette.',
  },
  {
    id: 'men-16',
    name: 'Nike Dunk Low Purple Grey',
    category: "Lifestyle",
    price: 125,
    image: '/shoe16.jpeg',
    colors: 3,
    description: 'Soft grey leather mixed with purple accents creates a clean modern sneaker rotation essential.',
  },
  {
    id: 'men-17',
    name: 'Nike SB Dunk Low Tokyo Inspired',
    category: "Skate Shoe",
    price: 145,
    image: '/shoe17.jpeg',
    colors: 2,
    description: 'A premium suede Dunk inspired by classic Tokyo-exclusive Nike SB aesthetics.',
  },
  {
    id: 'men-18',
    name: 'Nike Dunk Low Olive Grey',
    category: "Lifestyle",
    price: 130,
    image: '/shoe18.jpeg',
    colors: 2,
    description: 'Olive and grey tones combine for a rugged yet versatile Dunk Low streetwear look.',
  },
  {
    id: 'men-19',
    name: 'Nike Dunk Low Light Bone',
    category: "Lifestyle",
    price: 135,
    image: '/shoe19.jpeg',
    colors: 2,
    description: 'Neutral tones and soft leather textures make this Dunk Low perfect for daily styling.',
  },
  {
    id: 'men-20',
    name: 'Nike Killshot 2',
    category: "Vintage Shoe",
    price: 100,
    image: '/shoe20.jpeg',
    colors: 2,
    description: 'Retro tennis-inspired design with gum soles and minimalist vintage appeal.',
  },
  {
    id: 'men-21',
    name: 'Nike Dunk Low Grey Mint',
    category: "Lifestyle",
    price: 128,
    image: '/shoe21.jpeg',
    colors: 3,
    description: 'Fresh mint accents and neutral grey tones bring a modern refresh to the classic Dunk silhouette.',
  },
  {
    id: 'men-22',
    name: 'Travis Scott x Air Jordan 1 High Mocha',
    category: "Collaboration",
    price: 320,
    image: '/shoe22.jpeg',
    colors: 2,
    description: 'Featuring the iconic reverse swoosh and premium mocha suede, this AJ1 remains a grail sneaker.',
  },
    {
    id: 'men-23',
    name: 'Nike Dunk Low Grey Crimson',
    category: "Lifestyle",
    price: 130,
    image: '/shoe23.jpeg',
    colors: 2,
    description: 'A modern Dunk Low featuring grey overlays with bold crimson outsole accents.',
  },
  {
    id: 'men-24',
    name: 'Nike Dunk Low Grey Black',
    category: "Lifestyle",
    price: 128,
    image: '/shoe24.jpeg',
    colors: 2,
    description: 'Clean black and grey color blocking gives this Dunk a versatile everyday aesthetic.',
  },
  {
    id: 'men-25',
    name: 'Nike Dunk Low Panda Green',
    category: "Lifestyle",
    price: 135,
    image: '/shoe25.jpeg',
    colors: 3,
    description: 'A fresh twist on the Panda Dunk with green heel accents and classic monochrome styling.',
  },
  {
    id: 'men-26',
    name: 'Nike Dunk Low Photon Dust',
    category: "Lifestyle",
    price: 125,
    image: '/shoe26.jpeg',
    colors: 2,
    description: 'Soft grey tones and premium leather construction make this Dunk effortlessly wearable.',
  },
  {
    id: 'men-27',
    name: 'Nike Dunk Low Navy Brown',
    category: "Lifestyle",
    price: 132,
    image: '/shoe27.jpeg',
    colors: 2,
    description: 'Navy overlays paired with brown accents create a vintage-inspired streetwear vibe.',
  },
  {
    id: 'men-28',
    name: 'Nike Dunk Low University Blue',
    category: "Lifestyle",
    price: 145,
    image: '/shoe28.jpeg',
    colors: 2,
    description: 'Inspired by UNC colors with icy blue overlays and clean white leather panels.',
  },
  {
    id: 'men-29',
    name: 'Nike Dunk Low Tiffany Inspired',
    category: "Lifestyle",
    price: 150,
    image: '/shoe29.jpeg',
    colors: 2,
    description: 'A luxurious Dunk design inspired by iconic Tiffany turquoise color blocking.',
  },
  {
    id: 'men-30',
    name: 'Nike Dunk Low Taupe Grey',
    category: "Lifestyle",
    price: 130,
    image: '/shoe30.jpeg',
    colors: 2,
    description: 'Neutral taupe and grey tones combine for a clean minimalist sneaker rotation essential.',
  },
  {
    id: 'men-31',
    name: 'Air Jordan 1 Low Cherry',
    category: "Basketball Shoe",
    price: 140,
    image: '/shoe31.jpeg',
    colors: 2,
    description: 'Bold cherry red overlays bring classic Jordan heritage energy to this low-top silhouette.',
  },
  {
    id: 'men-32',
    name: 'Travis Scott x Air Jordan 1 High',
    category: "Collaboration",
    price: 320,
    image: '/shoe32.jpeg',
    colors: 3,
    description: 'Premium suede textures and signature reverse swoosh styling define this grail-worthy pair.',
  },
  {
    id: 'men-33',
    name: 'Air Jordan 1 Mid Orange',
    category: "Basketball Shoe",
    price: 150,
    image: '/shoe33.jpeg',
    colors: 2,
    description: 'Vibrant orange overlays and classic Jordan DNA create a standout everyday sneaker.',
  },
  {
    id: 'men-34',
    name: 'Nike Dunk Low Court Purple',
    category: "Lifestyle",
    price: 135,
    image: '/shoe34.jpeg',
    colors: 2,
    description: 'Court purple overlays and gum soles give this Dunk Low a bold retro basketball feel.',
  },
  {
    id: 'men-35',
    name: 'Air Jordan 1 Mid Yellow Toe',
    category: "Basketball Shoe",
    price: 165,
    image: '/shoe35.jpeg',
    colors: 3,
    description: 'The iconic Yellow Toe colorway delivers striking contrast and timeless Jordan appeal.',
  },
  {
    id: 'men-36',
    name: 'Air Jordan 1 High University Blue',
    category: "Basketball Shoe",
    price: 210,
    image: '/shoe36.jpeg',
    colors: 2,
    description: 'University blue overlays and premium leather elevate this AJ1 into a modern classic.',
  },
  {
    id: 'men-37',
    name: 'Air Jordan 1 High Bordeaux',
    category: "Basketball Shoe",
    price: 185,
    image: '/shoe37.jpeg',
    colors: 2,
    description: 'Rich burgundy overlays and crisp white leather deliver refined Jordan styling.',
  },
  {
    id: 'men-38',
    name: 'Air Jordan 1 High Taxi',
    category: "Basketball Shoe",
    price: 220,
    image: '/shoe38.jpeg',
    colors: 3,
    description: 'Black and yellow Taxi-inspired color blocking gives this AJ1 a bold streetwear presence.',
  },
  {
    id: 'men-39',
    name: 'Air Jordan 1 High Mocha',
    category: "Basketball Shoe",
    price: 230,
    image: '/shoe39.jpeg',
    colors: 2,
    description: 'Premium mocha suede overlays make this one of the cleanest and most sought-after AJ1 colorways.',
  },
  {
    id: 'men-40',
    name: 'Air Jordan 1 High Dark Mocha',
    category: "Basketball Shoe",
    price: 240,
    image: '/shoe40.jpeg',
    colors: 2,
    description: 'Dark mocha accents paired with black leather create a luxury-inspired Jordan aesthetic.',
  },
  {
    id: 'men-41',
    name: 'Nike Dunk High Panda',
    category: "Lifestyle",
    price: 145,
    image: '/shoe41.jpeg',
    colors: 2,
    description: 'The legendary Panda color scheme returns in a high-top Dunk silhouette.',
  },
  {
    id: 'men-42',
    name: 'Air Jordan 1 Low Shadow',
    category: "Basketball Shoe",
    price: 150,
    image: '/shoe42.jpeg',
    colors: 2,
    description: 'Shadow grey overlays and black leather create a sleek understated Jordan look.',
  },
];

// ==================== WOMEN'S PRODUCTS ====================
export const WOMEN_PRODUCTS: Product[] = [
  {
    id: 'women-1',
    name: 'Air Jordan 1 Mid Barely Rose',
    category: "Women's Lifestyle",
    price: 165,
    image: '/women1.jpeg',
    colors: 2,
    description: 'Soft pink overlays and premium leather give this AJ1 Mid a luxurious feminine aesthetic.',
    isNew: true
  },
  {
    id: 'women-2',
    name: 'Nike Dunk Low University Blue',
    category: "Women's Lifestyle",
    price: 145,
    image: '/women2.jpeg',
    colors: 2,
    description: 'Classic university blue overlays paired with crisp white leather panels for a timeless Dunk look.',
    isNew: false
  },
  {
    id: 'women-3',
    name: 'Nike Dunk Low Lavender',
    category: "Women's Shoe",
    price: 135,
    image: '/women3.jpeg',
    colors: 2,
    description: 'Pastel lavender overlays create a clean feminine take on the iconic Dunk Low silhouette.',
    isNew: true
  },
  {
    id: 'women-4',
    name: 'Nike Dunk Low Bordeaux',
    category: "Women's Lifestyle",
    price: 140,
    image: '/women4.jpeg',
    colors: 2,
    description: 'Rich burgundy overlays and vintage-inspired color blocking deliver elegant streetwear styling.',
    isNew: false
  },
  {
    id: 'women-5',
    name: 'Nike Air Force 1 Pink Foam',
    category: "Women's Lifestyle",
    price: 125,
    image: '/women5.jpeg',
    colors: 3,
    description: 'Soft pink tones and iconic AF1 cushioning make this pair perfect for everyday comfort and style.',
    isNew: true
  },
  {
    id: 'women-6',
    name: 'Nike Dunk Low Olive',
    category: "Women's Lifestyle",
    price: 130,
    image: '/women6.jpeg',
    colors: 2,
    description: 'Earthy olive overlays and premium leather details create a sleek neutral aesthetic.',
    isNew: false
  },
  {
    id: 'women-7',
    name: 'Nike Dunk Low Photon Dust',
    category: "Women's Lifestyle",
    price: 128,
    image: '/women7.jpeg',
    colors: 2,
    description: 'Clean grey overlays and subtle tones make this Dunk Low a versatile wardrobe essential.',
    isNew: true
  },
  {
    id: 'women-8',
    name: 'Nike Dunk Low Bordeaux White',
    category: "Women's Shoe",
    price: 132,
    image: '/women8.jpeg',
    colors: 2,
    description: 'A refined burgundy and white Dunk combination designed for everyday lifestyle wear.',
    isNew: false
  },
  {
    id: 'women-9',
    name: 'Nike Dunk Low Mocha',
    category: "Women's Lifestyle",
    price: 138,
    image: '/women9.jpeg',
    colors: 2,
    description: 'Warm mocha overlays paired with white leather give this Dunk a premium earthy finish.',
    isNew: true
  },
  {
    id: 'women-10',
    name: 'Nike Blazer Low Vintage',
    category: "Women's Vintage",
    price: 120,
    image: '/women10.jpeg',
    colors: 2,
    description: 'Retro basketball DNA meets minimalist styling in this timeless Nike Blazer Low.',
    isNew: false
  },
  {
    id: 'women-11',
    name: 'Nike Dunk Low Cacao Wow',
    category: "Women's Lifestyle",
    price: 145,
    image: '/women11.jpeg',
    colors: 2,
    description: 'Chocolate brown overlays and sail tones create one of the cleanest Dunk aesthetics.',
    isNew: true
  },
  {
    id: 'women-12',
    name: 'Nike SB Dunk Low Grey Olive',
    category: "Women's Skate",
    price: 150,
    image: '/women12.jpeg',
    colors: 2,
    description: 'Premium suede textures and muted olive accents give this SB Dunk a luxury skate vibe.',
    isNew: false
  },
  {
    id: 'women-13',
    name: 'Air Jordan 1 Low Bordeaux',
    category: "Women's Basketball",
    price: 155,
    image: '/women13.jpeg',
    colors: 2,
    description: 'Classic Jordan styling meets rich burgundy overlays for a clean low-top silhouette.',
    isNew: true
  },
  {
    id: 'women-14',
    name: 'Nike Dunk Low Pink Grey',
    category: "Women's Lifestyle",
    price: 130,
    image: '/women14.jpeg',
    colors: 3,
    description: 'Soft pink swooshes and grey overlays create a stylish modern Dunk Low palette.',
    isNew: false
  },
  {
    id: 'women-15',
    name: 'Nike Dunk Low Peach Cream',
    category: "Women's Shoe",
    price: 135,
    image: '/women15.jpeg',
    colors: 3,
    description: 'Peach overlays and cream midsoles combine for a fresh pastel-inspired sneaker look.',
    isNew: true
  },
  {
    id: 'women-16',
    name: 'Nike Dunk Low Pink Velvet',
    category: "Women's Lifestyle",
    price: 140,
    image: '/women16.jpeg',
    colors: 2,
    description: 'Velvet pink accents and soft suede textures elevate this Dunk Low into a standout pair.',
    isNew: false
  },
  {
    id: 'women-17',
    name: 'Nike Dunk Low Rose Pink',
    category: "Women's Lifestyle",
    price: 132,
    image: '/women17.jpeg',
    colors: 2,
    description: 'Rose pink overlays and crisp white leather create a feminine everyday sneaker essential.',
    isNew: true
  },
  {
    id: 'women-18',
    name: 'Nike Dunk Low Pink Taupe',
    category: "Women's Lifestyle",
    price: 136,
    image: '/women18.jpeg',
    colors: 2,
    description: 'Neutral taupe panels paired with blush pink details bring subtle elegance to the Dunk Low.',
    isNew: false
  },
  {
    id: 'women-19',
    name: 'Nike Dunk Low Royal Blue',
    category: "Women's Lifestyle",
    price: 145,
    image: '/women19.jpeg',
    colors: 2,
    description: 'Bold royal blue overlays give this Dunk Low a strong retro basketball-inspired aesthetic.',
    isNew: true
  },

  {
    id: 'women-20',
    name: 'Nike Dunk Low Beige Brown',
    category: "Women's Lifestyle",
    price: 138,
    image: '/women20.jpeg',
    colors: 2,
    description: 'Neutral beige and brown tones create a premium minimalist Dunk perfect for daily styling.',
    isNew: false
  },
];

// ==================== KIDS' PRODUCTS ====================
export const KIDS_PRODUCTS: Product[] = [
  {
    id: 'kids-1',
    name: 'Air Jordan 1 Low Panda',
    category: "Kids' Lifestyle",
    price: 85,
    image: '/kids1.jpeg',
    colors: 2,
    description: 'Classic black and white Air Jordan 1 Low made for everyday comfort and style.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-2',
    name: 'Air Jordan 1 Low Light Bone',
    category: "Kids' Lifestyle",
    price: 90,
    image: '/kids2.jpeg',
    colors: 2,
    description: 'Clean neutral tones with soft cushioning and premium low-top styling.',
    isNew: false,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-3',
    name: 'Air Jordan 1 Low Rust Orange',
    category: "Kids' Lifestyle",
    price: 88,
    image: '/kids3.jpeg',
    colors: 3,
    description: 'Bold rust orange overlays paired with classic Jordan heritage design.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-4',
    name: 'Air Jordan 1 Mid Bred Toe',
    category: "Kids' Basketball",
    price: 95,
    image: '/kids4.jpeg',
    colors: 3,
    description: 'Iconic red, white, and black color blocking inspired by classic Chicago style.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-5',
    name: 'Air Jordan 1 Low Wolf Grey',
    category: "Kids' Lifestyle",
    price: 92,
    image: '/kids5.jpeg',
    colors: 2,
    description: 'Minimal wolf grey finish with durable leather construction.',
    isNew: false,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-6',
    name: 'Nike Dunk Low Wheat',
    category: "Kids' Skateboarding",
    price: 78,
    image: '/kids6.jpeg',
    colors: 2,
    description: 'Earth-tone Nike Dunk Low with gum sole and premium suede finish.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-7',
    name: 'Air Jordan 1 Low Mocha',
    category: "Kids' Lifestyle",
    price: 94,
    image: '/kids7.jpeg',
    colors: 2,
    description: 'Soft mocha brown overlays inspired by one of the most loved Jordan colorways.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-8',
    name: 'Nike Dunk Low Navy Vintage',
    category: "Kids' Lifestyle",
    price: 82,
    image: '/kids8.jpeg',
    colors: 2,
    description: 'Retro navy and cream combination with timeless Dunk styling.',
    isNew: false,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-9',
    name: 'Air Jordan 1 Mid Pink Foam',
    category: "Kids' Lifestyle",
    price: 96,
    image: '/kids9.jpeg',
    colors: 3,
    description: 'Bright pink details mixed with clean white leather for standout style.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-10',
    name: 'Nike Air Force 1 Triple White',
    category: "Kids' Lifestyle",
    price: 100,
    image: '/kids10.jpeg',
    colors: 1,
    description: 'The timeless all-white Air Force 1 built for comfort and everyday wear.',
    isNew: false,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-11',
    name: 'Nike Dunk Low UNC',
    category: "Kids' Basketball",
    price: 89,
    image: '/kids11.jpeg',
    colors: 2,
    description: 'University blue overlays with classic Nike Dunk low-top design.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-12',
    name: 'Nike Dunk Low Cacao Wow',
    category: "Kids' Lifestyle",
    price: 87,
    image: '/kids12.jpeg',
    colors: 2,
    description: 'Chocolate brown tones with durable street-ready construction.',
    isNew: false,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-13',
    name: 'Nike Dunk Low Purple Pulse',
    category: "Kids' Lifestyle",
    price: 86,
    image: '/kids13.jpeg',
    colors: 3,
    description: 'Soft lavender overlays paired with crisp white leather panels.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-14',
    name: 'Nike Dunk Low Navy White',
    category: "Kids' Lifestyle",
    price: 84,
    image: '/kids14.jpeg',
    colors: 2,
    description: 'Classic navy and white combo with padded tongue comfort.',
    isNew: false,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-15',
    name: 'Nike Dunk Low Coconut Milk',
    category: "Kids' Lifestyle",
    price: 90,
    image: '/kids15.jpeg',
    colors: 2,
    description: 'Smooth cream tones with subtle brown detailing and retro appeal.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-16',
    name: 'Nike Dunk Low Grey Fog',
    category: "Kids' Lifestyle",
    price: 88,
    image: '/kids16.jpeg',
    colors: 2,
    description: 'Simple grey and white colorway designed for everyday rotation.',
    isNew: false,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-17',
    name: 'Nike Dunk Low Black Gum',
    category: "Kids' Skateboarding",
    price: 91,
    image: '/kids17.jpeg',
    colors: 2,
    description: 'Black upper paired with gum sole for a clean skate-inspired look.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-18',
    name: 'Nike Dunk Low Red Panda',
    category: "Kids' Lifestyle",
    price: 93,
    image: '/kids18.jpeg',
    colors: 3,
    description: 'Textured suede overlays with bold red accents and unique detailing.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-19',
    name: 'Air Jordan 1 Mid Shadow',
    category: "Kids' Basketball",
    price: 97,
    image: '/kids19.jpeg',
    colors: 2,
    description: 'A modern take on the classic Shadow colorway with premium materials.',
    isNew: false,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-20',
    name: 'Air Jordan 1 Mid Lucky Green',
    category: "Kids' Basketball",
    price: 99,
    image: '/kids20.jpeg',
    colors: 3,
    description: 'Fresh green overlays with classic Jordan mid-top support.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-21',
    name: 'Air Jordan 1 Mid Royal Blue',
    category: "Kids' Basketball",
    price: 98,
    image: '/kids21.jpeg',
    colors: 2,
    description: 'Bold royal blue finish inspired by iconic OG Jordan releases.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-22',
    name: 'Nike Court Borough Low Multi Color',
    category: "Kids' Lifestyle",
    price: 74,
    image: '/kids22.jpeg',
    colors: 5,
    description: 'Bright multicolor swooshes with sporty everyday comfort.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-23',
    name: 'Air Jordan 1 Low Dark Grey',
    category: "Kids' Lifestyle",
    price: 92,
    image: '/kids23.jpeg',
    colors: 2,
    description: 'Dark grey leather upper with sleek low-top silhouette.',
    isNew: false,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-24',
    name: 'Nike Court Borough Mid Neon',
    category: "Kids' Basketball",
    price: 80,
    image: '/kids24.jpeg',
    colors: 4,
    description: 'Neon green details mixed with black and yellow street style energy.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-25',
    name: 'Nike Dunk Low Olive Green',
    category: "Kids' Lifestyle",
    price: 90,
    image: '/kids25.jpeg',
    colors: 2,
    description: 'Olive green overlays with clean white leather panels and retro Nike styling.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-26',
    name: 'Air Jordan 1 Mid Ice Blue',
    category: "Kids' Basketball",
    price: 98,
    image: '/kids26.jpeg',
    colors: 3,
    description: 'Cool ice blue details paired with classic Jordan mid-top support.',
    isNew: false,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-27',
    name: 'Nike Dunk Low Sail Green',
    category: "Kids' Lifestyle",
    price: 86,
    image: '/kids27.jpeg',
    colors: 2,
    description: 'Soft sail base mixed with green overlays for a vintage-inspired finish.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-28',
    name: 'Air Force 1 White Red',
    category: "Kids' Lifestyle",
    price: 95,
    image: '/kids28.jpeg',
    colors: 2,
    description: 'Classic Air Force 1 silhouette with bold red swoosh accents.',
    isNew: false,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-29',
    name: 'Nike Dunk Low Forest Green',
    category: "Kids' Lifestyle",
    price: 88,
    image: '/kids29.jpeg',
    colors: 2,
    description: 'Forest green overlays with padded comfort and durable outsole grip.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-30',
    name: 'Air Jordan 1 Mid Black White',
    category: "Kids' Basketball",
    price: 97,
    image: '/kids30.jpeg',
    colors: 2,
    description: 'Monochrome Jordan styling built for everyday wear and comfort.',
    isNew: false,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-31',
    name: 'Nike Dunk Low Beige Brown',
    category: "Kids' Lifestyle",
    price: 89,
    image: '/kids31.jpeg',
    colors: 3,
    description: 'Neutral beige and brown tones with timeless Dunk low styling.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-32',
    name: 'Air Jordan 1 Low University Red',
    category: "Kids' Basketball",
    price: 96,
    image: '/kids32.jpeg',
    colors: 2,
    description: 'University red overlays inspired by iconic Jordan heritage colorways.',
    isNew: true,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  },
  {
    id: 'kids-33',
    name: 'Nike Dunk Low White Grey',
    category: "Kids' Lifestyle",
    price: 84,
    image: '/kids33.jpeg',
    colors: 2,
    description: 'White and grey finish with lightweight cushioning and retro streetwear appeal.',
    isNew: false,
    sizes: ['1Y', '2Y', '3Y', '4Y', '5Y', '6Y', '7Y']
  }
];

// ==================== ALL PRODUCTS (Combined for Shop Page) ====================
export const ALL_PRODUCTS: Product[] = [
  ...MEN_PRODUCTS,
  ...WOMEN_PRODUCTS,
  ...KIDS_PRODUCTS,
  // Premium/Jordan collection
  {
    id: 'premium-1',
    name: 'Nike Jordan 11 Retro',
    category: 'Lifestyle',
    price: 250,
    image: '/dick.jpeg',
    isNew: true,
    colors: 1,
    description: 'Celebrate the history of flight with one of the most beloved Air Jordan silhouettes of all time.',
    sizes: ['7', '8', '9', '10', '11', '12'],
    features: ['Patent leather upper', 'Carbon fiber shank', 'Full-length composite plate'],
  },
  {
    id: 'premium-2',
    name: 'Nike Jordan 6 Rings',
    category: 'Basketball',
    price: 190,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop',
    colors: 3,
    description: 'The Jordan 6 Rings incorporates key features from each shoe worn during MJ\'s championship series.',
    sizes: ['7', '8', '9', '10', '11', '12'],
    features: ['Zoom Air units', 'Phylon midsole', 'Genuine leather upper'],
  },
];

// ==================== TOP PICKS (For Homepage) ====================
export const TOP_PICKS: Product[] = MEN_PRODUCTS.slice(0, 4);

// ==================== HELPER FUNCTIONS ====================
export const getProductsByGender = (gender: 'men' | 'women' | 'kids') => {
  switch(gender) {
    case 'men':
      return MEN_PRODUCTS;
    case 'women':
      return WOMEN_PRODUCTS;
    case 'kids':
      return KIDS_PRODUCTS;
    default:
      return ALL_PRODUCTS;
  }
};

export const getProductById = (id: string) => {
  return ALL_PRODUCTS.find(product => product.id === id);
};

export const getProductsByCategory = (category: string) => {
  return ALL_PRODUCTS.filter(product => 
    product.category.toLowerCase().includes(category.toLowerCase())
  );
};